### PR TITLE
Add projects page with basic mockup

### PR DESCRIPTION
**Pull request by ajayns**
Addresses #10 

image

@sumedh123 @kvnamipara Please review

### CODE REVIEW

**Comment by kvnamipara** [comment]
@ajayns Looking good, Add appropriate links in navbar. we'll update content later

**Comment by ajayns** [comment]
Projects page navbar? Currently none of the pages have content in navbar yet. I've followed same layout as Meetups and Workshops page @kvnamipara

**Comment by kvnamipara** [comment]
We can just give link to go to homepage in left side of nav bar

**Comment by ajayns** [comment]
I'll add back buttons to all the navs when resolving #4 
@kvnamipara

**Pull request merged**
